# Generated by Django 4.2.5 on 2023-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='pngtree-super-selling-product-tag-png-image_4477856.png', upload_to='media/'),
        ),
    ]
